#!/bin/sh

if [ $# -lt 2 ]
then
	echo false
	exit 1
fi

if ! [ -f $1 ]
then
	echo false
	exit 1
fi

while IFS='=' read -r key value
do
	if [ $key == $2 ]
	then
		echo true
		exit 0
	fi
done <"$1"

echo false
exit 1
