#!/bin/sh

if [ $# -lt 2 ]
then
	echo ""
	exit 1
fi

if ! [ -f $1 ]
then
	echo ""
	exit 1
fi

while IFS='=' read -r key value
do
	if [ $key == $2 ]
	then
		echo $value
		exit 1
	fi
done <"$1"

echo ""
exit 1
